[package]
name = "wombat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
axum = "0.7.5"
clap = "4.5.17"
diesel = { version = "2.2.4", features = ["sqlite"] }
dotenvy = "0.15.7"
rand = "0.8.5"
serde = "1.0.210"
serenity = "0.12.2"
tokio = { version = "1.40.0", features = ["full"] }
tracing-subscriber = "0.3.18"
urlencoding = "2.1.3"
